name: dokit
description: 开发工具集
version: 0.8.2-nullsafety.10
homepage: https://www.dokit.cn/#/index/home


environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  date_format: ^2.0.7
  vm_service: ^11.4.0
  package_info: ^2.0.2
  shared_preferences: ^2.1.0
  image: ^4.0.15
  google_fonts: ^4.0.3
  string_scanner: ^1.2.0
  path_provider: ^2.0.14
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1


flutter:
  uses-material-design: true

  assets:
    - images/dokit_ic_close.png
    - images/dk_frame_hist.png
    - images/dk_method_channel.png
    - images/dk_sys_info.png
    - images/dk_view_check.png
    - images/dk_log_info.png
    - images/dk_ram.png
    - images/dk_view_route.png
    - images/dk_net_monitor.png
    - images/dokit_flutter_btn.png
    - images/dk_channel_check_h.png
    - images/dk_channel_check_n.png
    - images/dk_channel_expand_h.png
    - images/dk_channel_expand_n.png
    - images/dk_fps_chart.png
    - images/dk_route_arrow.png
    - images/dk_memory_search.png
    - images/dk_color_pick.png
    - images/dk_source_code.png
    - images/dk_time_counter.png
    - images/dokit_crash.png